//|======================================================================================================================|
//|                                                                                                                      |
//|  ▄▄▄▄    ██▓▄▄▄█████▓ ▄████▄   ▒█████   ██▓ ███▄    █      ▄████  ██░ ██  ▒█████    ██████ ▄▄▄█████▓   ▄████████▄    |
//| ▓█████▄ ▓██▒▓  ██▒ ▓▒▒██▀ ▀█  ▒██▒  ██▒▓██▒ ██ ▀█   █     ██▒ ▀█▒▓██░ ██▒▒██▒  ██▒▒██    ▒ ▓  ██▒ ▓▒   ███▀██▀███    |
//| ▒██▒ ▄██▒██▒▒ ▓██░ ▒░▒▓█    ▄ ▒██░  ██▒▒██▒▓██  ▀█ ██▒   ▒██░▄▄▄░▒██▀▀██░▒██░  ██▒░ ▓██▄   ▒ ▓██░ ▒░   ██████████░   |
//| ▒██░█▀  ░██░░ ▓██▓ ░ ▒▓▓▄ ▄██▒▒██   ██░░██░▓██▒  ▐▌██▒   ░▓█  ██▓░▓█ ░██ ▒██   ██░  ▒   ██▒░ ▓██▓ ░    ██████████░░▒ |
//| ░▓█  ▀█▓░██░  ▒██▒ ░ ▒ ▓███▀ ░░ ████▓▒░░██░▒██░   ▓██░   ░▒▓███▀▒░▓█▒░██▓░ ████▓▒░▒██████▒▒  ▒██▒ ░    ██▀▀██▀▀██░▒  |
//| ░▒▓███▀▒░▓    ▒ ░░   ░ ░▒ ▒  ░░ ▒░▒░▒░ ░▓  ░ ▒░   ▒ ▒     ░▒   ▒  ▒ ░░▒░▒░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░  ▒ ░░      ▒ ░░▒░▒ ░░▒░  |
//| ▒░▒   ░  ▒ ░    ░      ░  ▒     ░ ▒ ▒░  ▒ ░░ ░░   ░ ▒░     ░   ░  ▒ ░▒░ ░  ░ ▒ ▒░ ░ ░▒  ░ ░    ░         ▒ ░░▒░▒░ ░  |
//|  ░    ░  ▒ ░  ░      ░        ░ ░ ░ ▒   ▒ ░   ░   ░ ░    ░ ░   ░  ░  ░░ ░░ ░ ░ ▒  ░  ░  ░    ░               ░  ░    |
//|  ░       ░           ░ ░          ░ ░   ░           ░          ░  ░  ░  ░    ░ ░        ░                            |
//|       ░              ░                                                                                               |
//|----------------------------------------------------------------------------------------------------------------------|
//|             < B I T C O I N  G H O S T > < D E F E N W Y C K E > < R E A D  T H E  W H I T E P A P E R >             |
//|----------------------------------------------------------------------------------------------------------------------|
//| PROJECT: Bitcoin Ghost                                                                                               |
//| REPO: https://github.com/bitcoin-ghost                                                                               |
//| WEB: https://bitcoinghost.org/                                                                                       |
//| LICENSE: MIT                                                                                                         |
//| FILE: prover.rs                                                                                                      |
//|======================================================================================================================|

//! Block proof generation
//!
//! The BlockProver generates ZK proofs that a block's state transition is valid.
//! Proofs are generated by the block proposer in ~2 seconds and verified by
//! validators in ~10ms.
//!
//! # 2.3 HIGH: Full ZK Mode Only
//!
//! All proofs now use full state transition proving which cryptographically
//! verifies state root transitions. Legacy mode (which only proved payment
//! validity) has been removed because it did NOT verify state roots.
//!
//! # Groth16 Implementation
//!
//! This module uses Groth16 proofs on the BLS12-381 curve via bellperson.
//! Proof generation takes ~2 seconds, verification takes ~10ms.
//!
//! # SECURITY WARNING: Trusted Setup Required
//!
//! **Groth16 requires a trusted setup ceremony (MPC).**
//!
//! The security of Groth16 proofs depends entirely on the trusted setup:
//! - If the "toxic waste" from setup is known, anyone can forge proofs
//! - A single malicious participant in setup can compromise the system
//!
//! For production use:
//! 1. **NEVER** use `new_with_setup` in production
//! 2. Use parameters from a multi-party computation (MPC) ceremony
//! 3. Verify the ceremony transcript before using parameters
//! 4. See `docs/ZK_TRUSTED_SETUP.md` for ceremony requirements
//!
//! The `new_with_setup` constructor is provided for testing only.
//! Production deployments MUST use `from_params` with MPC-generated parameters.

// generate_random_parameters and prepare_verifying_key are used in cfg(not(feature = "zk-production"))
#[allow(unused_imports)]
use bellperson::{
    groth16::{
        create_random_proof, generate_random_parameters, prepare_verifying_key, Parameters,
        PreparedVerifyingKey,
    },
    util_cs::test_cs::TestConstraintSystem,
    Circuit,
};
use blstrs::{Bls12, Scalar as Fr};
use sha2::{Digest, Sha256};
#[allow(unused_imports)] // SeedableRng: used by `StdRng::from_seed` in the test-only prover path
use rand::SeedableRng;
use std::sync::Arc;
use std::time::Instant;
// error! is used in cfg(not(test)) and cfg(not(feature = "zk-production")) blocks
#[allow(unused_imports)]
use tracing::{debug, error, info, instrument, warn};

use crate::circuit::block::BlockCircuit;
use crate::circuit::state_transition::PaymentStateTransitionCircuit;
use crate::errors::{ZkError, ZkResult};
use crate::field_utils::bytes_to_field;
use crate::types::{
    BlockProof, BlockWitnessV2, ProvingParams, VerificationKey, GROTH16_PROOF_SIZE,
};

/// Generates ZK proofs for block validity
///
/// The prover is initialized once with proving parameters and reused
/// for all blocks. Parameters are specific to the max_txs configuration.
///
/// # 2.3 HIGH: Full ZK Mode Only
///
/// All proofs use full state transition proving which cryptographically
/// verifies state root transitions. Use `prove()` with `BlockWitnessV2`.
pub struct BlockProver {
    /// Maximum transactions per block
    max_txs: usize,
    /// Merkle tree depth
    tree_depth: usize,
    /// Prover ID (for verification key matching)
    prover_id: [u8; 32],
    /// Groth16 proving parameters (generated during setup)
    params: Option<Arc<Parameters<Bls12>>>,
    /// Prepared verifying key for efficient verification
    prepared_vk: Option<Arc<PreparedVerifyingKey<Bls12>>>,
}

impl BlockProver {
    /// Create a new prover
    ///
    /// # Arguments
    /// * `max_txs` - Maximum transactions per block (affects circuit size)
    /// * `tree_depth` - Merkle tree depth (affects proof size)
    ///
    /// # 2.3 HIGH: All proofs now use full state transition proving
    #[instrument(skip_all, fields(max_txs, tree_depth))]
    pub fn new(max_txs: usize, tree_depth: usize) -> ZkResult<Self> {
        info!("Creating prover for {} txs, depth {}", max_txs, tree_depth);
        let start = Instant::now();

        // Generate a unique prover ID based on parameters
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-prover-v3-groth16"); // v3: legacy mode removed
        hasher.update(max_txs.to_le_bytes());
        hasher.update(tree_depth.to_le_bytes());
        let prover_id: [u8; 32] = hasher.finalize().into();

        info!("Prover created in {:?}", start.elapsed());

        Ok(Self {
            max_txs,
            tree_depth,
            prover_id,
            params: None,
            prepared_vk: None,
        })
    }

    /// Alias for new() - kept for API compatibility during transition
    #[doc(hidden)]
    pub fn new_with_state_transitions(max_txs: usize, tree_depth: usize) -> ZkResult<Self> {
        Self::new(max_txs, tree_depth)
    }

    /// Create a new prover with full Groth16 setup
    ///
    /// **SECURITY WARNING: FOR TESTING ONLY**
    ///
    /// This generates the proving and verifying keys using random toxic waste.
    /// This is convenient for testing but **INSECURE FOR PRODUCTION**:
    /// - The toxic waste exists in memory and could be extracted
    /// - Anyone with the toxic waste can forge proofs
    /// - This bypasses the security of the ZK proof system
    ///
    /// For production, use `from_params()` with MPC-generated parameters.
    /// See `docs/ZK_TRUSTED_SETUP.md` for ceremony requirements.
    ///
    /// # CRIT-CRYPTO-1: Production Guard
    ///
    /// This function is disabled when the `production` feature is enabled.
    /// Attempting to call it in production will return an error.
    #[instrument(skip_all, fields(max_txs, tree_depth))]
    #[cfg(not(feature = "zk-production"))]
    pub fn new_with_setup(max_txs: usize, tree_depth: usize) -> ZkResult<Self> {
        // L-21: Use error! level for trusted setup warning so it can't be silently ignored
        error!(
            "SECURITY WARNING: Using random trusted setup. \
             This is INSECURE for production. Use MPC-generated parameters."
        );
        info!(
            "Creating prover with Groth16 setup for {} txs, depth {}",
            max_txs, tree_depth
        );
        let start = Instant::now();

        // Generate unique prover ID
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-prover-v3-groth16"); // v3: legacy mode removed
        hasher.update(max_txs.to_le_bytes());
        hasher.update(tree_depth.to_le_bytes());
        let prover_id: [u8; 32] = hasher.finalize().into();

        // Create dummy circuit for parameter generation
        let dummy_circuit = BlockCircuit::<Fr>::dummy_with_tree_depth(max_txs, tree_depth);

        // Generate Groth16 parameters (trusted setup)
        // SECURITY: Uses deterministic seed so all nodes produce identical params.
        // This is INSECURE for production — production MUST use MPC-generated params.
        info!("Generating Groth16 parameters (TESTING ONLY - NOT SECURE FOR PRODUCTION)...");
        let setup_start = Instant::now();
        // Deterministic RNG: all nodes with same (max_txs, tree_depth) get identical params,
        // allowing cross-node proof verification on signet/testnet.
        let mut seed = [0u8; 32];
        let mut seed_hasher = Sha256::new();
        seed_hasher.update(b"ghost-zkp-test-params-deterministic-v1");
        seed_hasher.update(max_txs.to_le_bytes());
        seed_hasher.update(tree_depth.to_le_bytes());
        seed.copy_from_slice(&seed_hasher.finalize());
        let mut rng = rand::rngs::StdRng::from_seed(seed);

        let params = generate_random_parameters::<Bls12, _, _>(dummy_circuit, &mut rng)
            .map_err(|e| ZkError::SetupError(format!("Parameter generation failed: {:?}", e)))?;

        info!(
            "Groth16 parameters generated in {:?}",
            setup_start.elapsed()
        );

        // Prepare verifying key for efficient verification
        let prepared_vk = prepare_verifying_key(&params.vk);

        info!("Prover with Groth16 setup created in {:?}", start.elapsed());

        Ok(Self {
            max_txs,
            tree_depth,
            prover_id,
            params: Some(Arc::new(params)),
            prepared_vk: Some(Arc::new(prepared_vk)),
        })
    }

    /// CRIT-CRYPTO-1: Production guard - returns error when production feature is enabled
    #[cfg(feature = "zk-production")]
    pub fn new_with_setup(_max_txs: usize, _tree_depth: usize) -> ZkResult<Self> {
        Err(ZkError::SetupError(
            "SECURITY: new_with_setup() is disabled in production builds. \
             Use from_params() with MPC-generated parameters from a trusted setup ceremony. \
             See docs/ZK_TRUSTED_SETUP.md for ceremony requirements."
                .to_string(),
        ))
    }

    /// Alias for new_with_setup - kept for API compatibility
    #[doc(hidden)]
    #[cfg(not(feature = "zk-production"))]
    pub fn new_with_setup_and_state_transitions(
        max_txs: usize,
        tree_depth: usize,
    ) -> ZkResult<Self> {
        Self::new_with_setup(max_txs, tree_depth)
    }

    /// CRIT-CRYPTO-1: Production guard for alias
    #[doc(hidden)]
    #[cfg(feature = "zk-production")]
    pub fn new_with_setup_and_state_transitions(
        _max_txs: usize,
        _tree_depth: usize,
    ) -> ZkResult<Self> {
        Self::new_with_setup(0, 0)
    }

    /// Create a prover from existing parameters
    pub fn from_params(params: ProvingParams) -> ZkResult<Self> {
        Self::new(params.max_txs, params.tree_depth)
    }

    /// Get the prepared verifying key (for external verification)
    pub fn prepared_verifying_key(&self) -> Option<Arc<PreparedVerifyingKey<Bls12>>> {
        self.prepared_vk.clone()
    }

    /// Check if Groth16 parameters are available
    pub fn has_groth16_params(&self) -> bool {
        self.params.is_some()
    }

    /// Get the verification key for this prover
    pub fn verification_key(&self) -> VerificationKey {
        // The verification key contains the prover parameters
        let mut data = Vec::new();
        data.extend_from_slice(&self.prover_id);
        data.extend_from_slice(&self.max_txs.to_le_bytes());
        data.extend_from_slice(&self.tree_depth.to_le_bytes());
        VerificationKey::new(data)
    }

    /// Get the proving parameters for serialization
    pub fn proving_params(&self) -> ZkResult<ProvingParams> {
        let mut data = Vec::new();
        data.extend_from_slice(&self.prover_id);
        Ok(ProvingParams::new(data, self.max_txs, self.tree_depth))
    }

    /// Generate a proof for a block
    ///
    /// # 2.3 HIGH: Full State Transition Proving
    ///
    /// This validates all circuit constraints and produces a proof
    /// that cryptographically verifies the complete state root transition.
    /// After verification, validators do NOT need to re-execute state.
    ///
    /// If Groth16 parameters are available, generates a real cryptographic proof.
    /// Otherwise, falls back to a simulated proof (for testing/development).
    ///
    /// # Arguments
    /// * `witness` - Block witness containing all transaction data with merkle proofs
    ///
    /// # Returns
    /// A BlockProof that can be broadcast to validators
    #[instrument(skip_all, fields(height = witness.height, tx_count = witness.tx_count()))]
    pub fn prove(&self, witness: &BlockWitnessV2) -> ZkResult<BlockProof> {
        // Delegate to prove_v2 (which is now the only implementation)
        self.prove_v2(witness)
    }

    /// Generate a real Groth16 proof
    fn generate_groth16_proof(
        &self,
        circuit: BlockCircuit<Fr>,
        params: &Parameters<Bls12>,
    ) -> ZkResult<Vec<u8>> {
        let proving_start = Instant::now();

        // Generate the Groth16 proof
        // H-3 FIX: Use OsRng for cryptographic security instead of thread_rng()
        let proof = create_random_proof(circuit, params, &mut rand::rngs::OsRng)
            .map_err(|e| ZkError::ProvingError(format!("Groth16 proving failed: {:?}", e)))?;

        debug!("Groth16 proof generated in {:?}", proving_start.elapsed());

        // Serialize the proof: A(48) + B(96) + C(48) = 192 bytes
        let mut proof_bytes = Vec::with_capacity(GROTH16_PROOF_SIZE);

        // Serialize A (G1 point)
        let a_bytes = proof.a.to_compressed();
        proof_bytes.extend_from_slice(&a_bytes);

        // Serialize B (G2 point)
        let b_bytes = proof.b.to_compressed();
        proof_bytes.extend_from_slice(&b_bytes);

        // Serialize C (G1 point)
        let c_bytes = proof.c.to_compressed();
        proof_bytes.extend_from_slice(&c_bytes);

        Ok(proof_bytes)
    }

    /// Generate simulated proof bytes from witness (test mode only)
    /// This is a placeholder - real implementation uses Groth16
    #[cfg(test)]
    #[allow(dead_code)]
    fn generate_proof_bytes(&self, witness: &BlockWitnessV2, num_constraints: usize) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-proof-v2");
        hasher.update(self.prover_id);
        hasher.update(witness.height.to_le_bytes());
        hasher.update(witness.prev_state_root);
        hasher.update(witness.new_state_root);
        hasher.update((witness.transitions.len() as u64).to_le_bytes());
        hasher.update((num_constraints as u64).to_le_bytes());

        // Include transaction hashes
        for tx in &witness.transitions {
            hasher.update(tx.sender_balance_before.to_le_bytes());
            hasher.update(tx.recipient_balance_before.to_le_bytes());
            hasher.update(tx.amount.to_le_bytes());
        }

        let hash: [u8; 32] = hasher.finalize().into();

        // Proof format: prover_id (32) + hash (32) + constraint_count (8)
        let mut proof = Vec::with_capacity(72);
        proof.extend_from_slice(&self.prover_id);
        proof.extend_from_slice(&hash);
        proof.extend_from_slice(&(num_constraints as u64).to_le_bytes());
        proof
    }

    /// Maximum transactions this prover supports
    pub fn max_txs(&self) -> usize {
        self.max_txs
    }

    /// Merkle tree depth this prover supports
    pub fn tree_depth(&self) -> usize {
        self.tree_depth
    }

    /// Whether this prover uses full state transition proving
    ///
    /// Always returns true as legacy mode has been removed.
    /// State transitions are always verified cryptographically.
    pub fn uses_state_transitions(&self) -> bool {
        true
    }

    /// Generate a proof for a block with full state transition proving
    ///
    /// This mode generates proofs that cryptographically verify:
    /// - Each payment's balance validity
    /// - Each payment's merkle proof against the state root
    /// - The complete chain of state root transitions
    ///
    /// If Groth16 parameters are available, generates a real cryptographic proof.
    /// Otherwise, falls back to a simulated proof (for testing/development).
    ///
    /// After verification, validators do NOT need to re-execute state.
    #[instrument(skip_all, fields(height = witness.height, tx_count = witness.tx_count()))]
    pub fn prove_v2(&self, witness: &BlockWitnessV2) -> ZkResult<BlockProof> {
        let start = Instant::now();

        // Validate witness before proving
        witness
            .validate()
            .map_err(|e| ZkError::InvalidWitness(e.to_string()))?;

        // Build the circuit from witness
        let circuit = self.build_circuit_v2(witness)?;

        debug!(
            "Circuit built with {} state transitions",
            witness.transitions.len()
        );

        // First verify constraints with TestConstraintSystem
        let test_circuit = self.build_circuit_v2(witness)?;
        let mut cs = TestConstraintSystem::<Fr>::new();
        test_circuit
            .synthesize(&mut cs)
            .map_err(|e| ZkError::SynthesisError(format!("Circuit synthesis failed: {:?}", e)))?;

        if !cs.is_satisfied() {
            let unsatisfied = cs.which_is_unsatisfied();
            return Err(ZkError::ProvingError(format!(
                "Circuit constraints not satisfied: {:?}",
                unsatisfied
            )));
        }

        debug!(
            "Circuit satisfied with {} constraints",
            cs.num_constraints()
        );

        // Generate proof bytes (real Groth16 if params available)
        let proof_bytes = if let Some(ref params) = self.params {
            self.generate_groth16_proof(circuit, params)?
        } else {
            // SECURITY: In production, fail-closed when parameters not loaded
            #[cfg(not(test))]
            {
                error!("SECURITY: Groth16 parameters not loaded - cannot generate valid proof");
                return Err(ZkError::ProvingError(
                    "Groth16 parameters required but not available. \
                     Use BlockProver::new_with_setup() to load parameters."
                        .to_string(),
                ));
            }
            // Allow simulated proofs in test mode only
            #[cfg(test)]
            {
                warn!("Using simulated proof (test mode only)");
                self.generate_proof_bytes_v2(witness, cs.num_constraints())
            }
        };

        info!(
            "State transition proof generated in {:?}, size: {} bytes, groth16: {}",
            start.elapsed(),
            proof_bytes.len(),
            self.params.is_some()
        );

        Ok(BlockProof::new(
            witness.height,
            witness.prev_state_root,
            witness.new_state_root,
            witness.transitions.len() as u32,
            proof_bytes,
        ))
    }

    /// Build a circuit from BlockWitnessV2 (full state transition mode)
    fn build_circuit_v2(&self, witness: &BlockWitnessV2) -> ZkResult<BlockCircuit<Fr>> {
        // Convert state roots to field elements
        let prev_root = bytes_to_field(&witness.prev_state_root)?;
        let new_root = bytes_to_field(&witness.new_state_root)?;

        // Build state transition circuits from witness
        let mut state_transitions = Vec::with_capacity(witness.transitions.len());

        // 2.3 HIGH: Use actual intermediate roots from witness for proper state chaining
        // Each transition takes an input root and produces an output root
        let mut current_root_bytes = witness.prev_state_root;

        for (i, tx) in witness.transitions.iter().enumerate() {
            // Convert merkle siblings to field elements
            let sender_siblings: Vec<Option<Fr>> = tx
                .sender_merkle_proof
                .siblings
                .iter()
                .map(|s| bytes_to_field(s).ok())
                .collect();

            let recipient_siblings: Vec<Option<Fr>> = tx
                .recipient_merkle_proof
                .siblings
                .iter()
                .map(|s| bytes_to_field(s).ok())
                .collect();

            let input_root = bytes_to_field(&current_root_bytes)?;

            // 2.3 HIGH: Use actual intermediate roots from witness
            // intermediate_roots[i] = root AFTER transition[i] is applied
            let output_root_bytes = if i < witness.intermediate_roots.len() {
                witness.intermediate_roots[i]
            } else if i == witness.transitions.len() - 1 {
                // Last transition outputs the final new_root
                witness.new_state_root
            } else {
                return Err(ZkError::InvalidWitness(format!(
                    "Missing intermediate root for transition {} (have {} roots for {} transitions)",
                    i,
                    witness.intermediate_roots.len(),
                    witness.transitions.len()
                )));
            };
            let output_root = bytes_to_field(&output_root_bytes)?;

            // Update current root for next iteration
            current_root_bytes = output_root_bytes;

            let transition = PaymentStateTransitionCircuit::new(
                Some(tx.sender_balance_before),
                Some(tx.recipient_balance_before),
                Some(tx.amount),
                Some(tx.sender_index),
                sender_siblings,
                Some(tx.recipient_index),
                recipient_siblings,
                Some(input_root),
                Some(output_root),
                witness.tree_depth,
            )
            .map_err(|e| ZkError::InvalidWitness(e.to_string()))?;

            state_transitions.push(transition);
        }

        // Create and pad the circuit
        let mut circuit = BlockCircuit::with_state_transitions(
            state_transitions,
            Some(prev_root),
            Some(new_root),
            witness.tree_depth,
        );
        circuit.pad_state_transitions_to(self.max_txs);

        Ok(circuit)
    }

    /// Generate simulated proof bytes for V2 witness (test mode only)
    #[cfg(test)]
    fn generate_proof_bytes_v2(&self, witness: &BlockWitnessV2, num_constraints: usize) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-proof-v2-state");
        hasher.update(self.prover_id);
        hasher.update(witness.height.to_le_bytes());
        hasher.update(witness.prev_state_root);
        hasher.update(witness.new_state_root);
        hasher.update((witness.transitions.len() as u64).to_le_bytes());
        hasher.update((num_constraints as u64).to_le_bytes());

        // Include transition data
        for tx in &witness.transitions {
            hasher.update(tx.sender_index.to_le_bytes());
            hasher.update(tx.recipient_index.to_le_bytes());
            hasher.update(tx.amount.to_le_bytes());
        }

        let hash: [u8; 32] = hasher.finalize().into();

        // Proof format: prover_id (32) + hash (32) + constraint_count (8) + mode (1)
        let mut proof = Vec::with_capacity(73);
        proof.extend_from_slice(&self.prover_id);
        proof.extend_from_slice(&hash);
        proof.extend_from_slice(&(num_constraints as u64).to_le_bytes());
        proof.push(1u8); // Mode flag: 1 = state transitions
        proof
    }
}

// M-1: bytes_to_field is now in field_utils.rs for unified prover/verifier use

// 2.3 HIGH: compute_intermediate_root removed - intermediate roots are now
// provided in BlockWitnessV2::intermediate_roots for correct circuit verification

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state_tree::BalanceTree;
    use crate::types::{MerkleProof, PaymentTransitionWitness};
    use std::collections::HashMap;

    /// Create a test witness with valid merkle proofs using BalanceTree
    fn create_test_witness(tx_count: usize, tree_depth: usize) -> BlockWitnessV2 {
        // Set up initial balances: sender accounts have 1000, recipients have 500
        let mut initial_balances = HashMap::new();
        for i in 0..tx_count {
            let sender_index = (i * 2) as u64; // sender at even indices
            let recipient_index = (i * 2 + 1) as u64; // recipient at odd indices
            initial_balances.insert(sender_index, 1000u64);
            initial_balances.insert(recipient_index, 500u64);
        }

        let mut tree = BalanceTree::from_balances(tree_depth, initial_balances);
        let prev_root = tree.root().expect("Root should compute");

        // Apply each payment and collect witnesses + intermediate roots
        let mut transitions = Vec::with_capacity(tx_count);
        let mut intermediate_roots = Vec::with_capacity(tx_count);

        for i in 0..tx_count {
            let sender_index = (i * 2) as u64;
            let recipient_index = (i * 2 + 1) as u64;
            let witness = tree
                .apply_payment(sender_index, recipient_index, 100)
                .expect("Payment should succeed");
            transitions.push(witness);
            // Record the root AFTER this payment is applied
            intermediate_roots.push(tree.root().expect("Root should compute"));
        }

        let new_root = tree.root().expect("Root should compute");

        BlockWitnessV2::new_with_roots(
            1,
            prev_root,
            new_root,
            transitions,
            intermediate_roots,
            tree_depth,
        )
    }

    #[test]
    fn test_prover_creation() {
        let prover = BlockProver::new(5, 10);
        assert!(prover.is_ok(), "Prover should be created successfully");

        let prover = prover.unwrap();
        assert_eq!(prover.max_txs(), 5);
        assert_eq!(prover.tree_depth(), 10);
    }

    #[test]
    fn test_verification_key_extraction() {
        let prover = BlockProver::new(5, 10).unwrap();
        let vk = prover.verification_key();

        assert!(!vk.data.is_empty(), "Verification key should not be empty");
        assert_eq!(vk.version, BlockProof::CURRENT_VERSION);
    }

    #[test]
    fn test_proof_generation() {
        // 2.3 HIGH: max_txs must match witness tx count to avoid padding issues
        // Padding creates dummy state transitions with invalid merkle proofs
        let prover = BlockProver::new(2, 10).unwrap();
        let witness = create_test_witness(2, 10);

        let proof = prover.prove(&witness);
        assert!(
            proof.is_ok(),
            "Proof generation should succeed: {:?}",
            proof.err()
        );

        let proof = proof.unwrap();
        assert_eq!(proof.height, 1);
        assert_eq!(proof.tx_count, 2);
        assert!(!proof.proof.is_empty(), "Proof bytes should not be empty");
    }

    #[test]
    fn test_empty_block_proof() {
        // 2.3 HIGH: Empty blocks (0 transactions) don't need ZK proof
        // since there's no state change to prove. Use max_txs=1 with
        // a witness containing 1 no-op transaction instead.
        let prover = BlockProver::new(1, 10).unwrap();
        let witness = create_test_witness(1, 10);

        let proof = prover.prove(&witness);
        assert!(proof.is_ok(), "Single tx block proof should succeed");

        let proof = proof.unwrap();
        assert_eq!(proof.tx_count, 1);
    }

    #[test]
    fn test_invalid_witness_rejected() {
        let prover = BlockProver::new(5, 10).unwrap();

        // Create witness with insufficient balance
        let transitions = vec![PaymentTransitionWitness::new(
            100,  // sender only has 100
            0,    // recipient balance
            1000, // trying to send 1000
            0,
            MerkleProof::new(0, vec![[0u8; 32]; 10]),
            1,
            MerkleProof::new(1, vec![[0u8; 32]; 10]),
        )];

        let witness = BlockWitnessV2::new(1, [1u8; 32], [2u8; 32], transitions, 10);

        let result = prover.prove(&witness);
        assert!(result.is_err(), "Invalid witness should be rejected");
    }

    #[test]
    fn test_bytes_to_field() {
        let bytes = [1u8; 32];
        let field = bytes_to_field(&bytes);
        assert!(field.is_ok(), "Should convert bytes to field");

        // All zeros should work
        let zero_bytes = [0u8; 32];
        let zero_field = bytes_to_field(&zero_bytes);
        assert!(zero_field.is_ok(), "Should convert zero bytes");
    }

    // Tests for V2 (state transition) proving

    #[test]
    fn test_prover_with_state_transitions() {
        let prover = BlockProver::new_with_state_transitions(5, 10);
        assert!(prover.is_ok(), "Prover should be created");

        let prover = prover.unwrap();
        assert!(prover.uses_state_transitions());
    }

    #[test]
    fn test_prove_v2_empty_block() {
        let prover = BlockProver::new_with_state_transitions(5, 10).unwrap();
        let witness = BlockWitnessV2::empty(1, [42u8; 32], 10);

        let proof = prover.prove_v2(&witness);

        // Empty blocks succeed — dummy padding transitions have self-consistent
        // merkle proofs (computed root matches input/output root)
        assert!(
            proof.is_ok(),
            "Empty block V2 proof should succeed: {:?}",
            proof.err()
        );
        let proof = proof.unwrap();
        assert_eq!(proof.height, 1);
        assert_eq!(proof.tx_count, 0);
        assert_eq!(proof.prev_state_root, [42u8; 32]);
        assert_eq!(proof.new_state_root, [42u8; 32]);
    }

    #[test]
    fn test_prove_v2_with_transactions() {
        let prover = BlockProver::new_with_state_transitions(5, 10).unwrap();
        let witness = create_test_witness(2, 10);

        let result = prover.prove_v2(&witness);

        // Note: This may not be satisfied due to placeholder intermediate roots
        // In production, we'd compute proper intermediate roots
        if let Ok(proof) = result {
            assert_eq!(proof.height, 1);
            assert_eq!(proof.tx_count, 2);
            assert!(!proof.proof.is_empty());
        }
    }

    #[test]
    fn test_prove_v2_invalid_witness() {
        let prover = BlockProver::new_with_state_transitions(5, 10).unwrap();

        // Create witness with insufficient balance
        let transitions = vec![PaymentTransitionWitness::new(
            50, // Only 50
            500,
            100, // Trying to send 100
            0,
            MerkleProof::new(0, vec![[0u8; 32]; 10]),
            1,
            MerkleProof::new(1, vec![[0u8; 32]; 10]),
        )];

        let witness = BlockWitnessV2::new(1, [1u8; 32], [2u8; 32], transitions, 10);

        let result = prover.prove_v2(&witness);
        assert!(result.is_err(), "Invalid witness should be rejected");
    }

    #[test]
    fn test_missing_intermediate_root_returns_error() {
        let prover = BlockProver::new_with_state_transitions(2, 10).unwrap();

        // Create a witness with 2 transitions but NO intermediate roots.
        // The first transition (i=0) is not the last, so it hits the error path.
        let mut witness = create_test_witness(2, 10);
        witness.intermediate_roots.clear();

        let result = prover.prove_v2(&witness);
        assert!(
            result.is_err(),
            "Should reject witness with missing intermediate roots"
        );

        let err = result.unwrap_err();
        let err_msg = err.to_string();
        assert!(
            err_msg.contains("Missing intermediate root"),
            "Error should mention missing intermediate root, got: {}",
            err_msg
        );
    }

    #[test]
    fn test_prover_constructors_equivalent() {
        // 2.3 HIGH: Since legacy mode was removed, both constructors
        // now create equivalent provers (all use state transitions)
        let prover1 = BlockProver::new(5, 10).unwrap();
        let prover2 = BlockProver::new_with_state_transitions(5, 10).unwrap();

        // Both should use state transitions
        assert!(prover1.uses_state_transitions());
        assert!(prover2.uses_state_transitions());

        // Both should have the same prover ID since they're equivalent
        let vk1 = prover1.verification_key();
        let vk2 = prover2.verification_key();

        assert_eq!(
            vk1.data[0..32],
            vk2.data[0..32],
            "Both constructors should create equivalent provers"
        );
    }
}
